[package]
name = "ScrapperRust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
thirtyfour = "0.32"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"
rand = "0.8"
futures = "0.3"
